#!/bin/bash
#!/bin/bash
curl https://registry.npmjs.org/lesshat/-/lesshat-4.1.0.tgz > test-resources/lesshat.tgz
cd test-resources
tar -xzf lesshat.tgz
rm lesshat.tgz
mv package/* lesshat
rmdir package
cd ..

