#!/bin/bash
newerless=`find resources/change-me-to-project-name/css -cnewer resources/change-me-to-project-name/css/change-me-to-project-name.css -name '*.less'`
if [ ${#newerless} -ne 0 ] 
then
	echo 'building less'
	echo 'Pages css errors:' > css-build-errors.txt
	lessc resources/change-me-to-project-name/css/change-me-to-project-name.less > resources/change-me-to-project-name/css/change-me-to-project-name.css 2>> css-build-errors.txt
fi

newerless=`find test-resources -cnewer test-resources/test.css -name '*.less'`
if [ ${#newerless} -ne 0 ] 
then
	echo 'building test less'
	echo 'Test css errors:' >> css-build-errors.txt
	lessc test-resources/test.less > test-resources/test.css 2>> css-build-errors.txt
fi

newerjs=`find resources/change-me-to-project-name/js -cnewer resources/change-me-to-project-name/js/plugin.js -name '*.js'`
newertmpl=`find resources/change-me-to-project-name/js/templates -cnewer resources/change-me-to-project-name/js/plugin.js -name '*.tmpl'`
if [ ${#newerjs} -ne 0 ] || [ ${#newertmpl} -ne 0 ]
then
echo 'building js'
cd resources/change-me-to-project-name/js
node_modules/browserify/bin/cmd.js -d index.js > plugin.debug.js 2> ../js-build-errors.txt
node_modules/browserify/bin/cmd.js index.js > plugin.js
cd ../../..
fi
