#!/bin/bash
packagefiles=`find dep-resources -name 'package.json'`
cd resources/change-me-to-project-name/js
for pn in $packagefiles
do
	noderepo=`dirname $pn`
	echo $noderepo
	relnoderepo="../../..$noderepo"
	npm install "$relnoderepo"
done
npm install
